### ISSUE TITLE
Create f001 package with all colors

### ISSUE THREAD

**Issue by vovayatsyuk** [tmhub/templatef001#1]
This will dramatically decrease files count and will make more easier to upgrade theme and integrate third-party modules.

**Comment by dimdimich** [comment]
It would be also great to convert all xml files to one local.xml instead of overwriting core xml files.

**Comment by vovayatsyuk** [comment]
Separate package added: a4b84ba0ab3e3c76ff5605074053102bb5a7faa5
Removed old theme: b145108e140bcbb347d31c07d532dc008e30d437
